### ISSUE TITLE
Description not shown...

### ISSUE THREAD

**Issue by Snille** [brobergp/MMM-newsfeedtouch#1]
Hi, thank you for this nice module! :)

I'm using it with multiple news feeds.
For this one: http://www.hd.se/rss.xml?latest=1
The description does not show (only a black empty container show up when clicking).

But this one works as expected: http://feber.se/pryl/rss/

Hopefully you can figure out why. :)
Thank you.

**Comment by brobergp** [comment]
Hi, Sorry for the long wait for feedback, github doesn't send me any notifications when something happens.

Anyhow, the hd.se rss feed doesn't use the "description" tag in their feed, that's why you don't get anything displayed.
