### ISSUE TITLE
The windows of news content is beyond the boundaries of the screen when news content is too long

### ISSUE THREAD

**Issue by xuepgao** [brobergp/MMM-newsfeedtouch#4]
Hi @brobergp 

Thank you for providing us with this fantastic module!
Everything works fine except for a windows display problem. The windows of news content is beyond the boundaries of the screen when the news content is too long. Please find the screenshot is as following link: [https://drive.google.com/open?id=1b737LJ8SJpjWm5hWLXfcWAApJoSb_VQ-](https://drive.google.com/open?id=1b737LJ8SJpjWm5hWLXfcWAApJoSb_VQ-)

Could you give me some suggestion?  I've adjusted the font size down.

Thanks again for your module!

**Comment by brobergp** [comment]
Try adding

```
.infoCenter { 
height: 40%;
overflow: hidden;
}
```

To your custom.css

This should hide the overflow when the description is to big.
If you change `overflow: hidden` to `overflow: scroll` you should get a scrollbar in the box.

Haven't tried this myself but it's the first thing that came to mind.

**Comment by xuepgao** [comment]
Hi @brobergp 

According to your suggestion, I've resolved this issue.
Thank you so much!
